menu:
 Home: /
 Twitter: https://twitter.com/dsosby
 Github: https://github.com/dsosby

widgets:
 - gravatar
 - site_links

rss: /atom.xml

readMore: ...read more

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:

tag_generator:
  per_page: 10
